#!/usr/bin/env node
// Generates design-token outputs from the Figma snapshot.
//
//   input : src/styles/tokens/figma-export.json  (Figma "New-Hockia" variables)
//   output: src/styles/tokens/tokens.css         (CSS custom properties)
//           src/styles/tokens/tokens.js          (plain values for tailwind.config.js)
//
// tokens.js is read by tailwind.config.js at build time only; it is never
// imported by app code, so it adds nothing to the runtime bundle.
// Usage: node scripts/build-tokens.mjs  (or: npm run tokens:build)

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'styles', 'tokens')
const src = JSON.parse(readFileSync(join(dir, 'figma-export.json'), 'utf8'))

const header = '/* GENERATED by scripts/build-tokens.mjs from figma-export.json — do not edit by hand. */\n'
const cssName = (name) => name.replace(/\//g, '-')

// ── tokens.css ──────────────────────────────────────────────────────────────
const lines = []
for (const [name, value] of Object.entries(src.color)) lines.push(`  --${cssName(name)}: ${value};`)
for (const [k, v] of Object.entries(src.space)) lines.push(`  --space-${k}: ${v}px;`)
for (const [k, v] of Object.entries(src.radius)) lines.push(`  --radius-${k}: ${v}px;`)
for (const [k, t] of Object.entries(src.text)) {
  lines.push(`  --text-${k}-size: ${t.size}px;`)
  lines.push(`  --text-${k}-line-height: ${t.lineHeight}px;`)
  lines.push(`  --text-${k}-weight: ${t.weight};`)
}
for (const [k, v] of Object.entries(src.shadow)) lines.push(`  --shadow-${k}: ${v};`)
writeFileSync(join(dir, 'tokens.css'), `${header}:root {\n${lines.join('\n')}\n}\n`)

// ── tokens.js (nested colours for Tailwind) ─────────────────────────────────
const colors = {}
for (const [name, value] of Object.entries(src.color)) {
  const [group, key] = name.split('/')
  ;(colors[group] ||= {})[key] = value
}
const js =
  header.replace('/*', '//').replace(' */', '') +
  `export const colors = ${JSON.stringify(colors, null, 2)}\n\n` +
  `export const space = ${JSON.stringify(src.space, null, 2)}\n\n` +
  `export const radius = ${JSON.stringify(src.radius, null, 2)}\n`
writeFileSync(join(dir, 'tokens.js'), js)

console.log(`tokens: ${Object.keys(src.color).length} colours, ${Object.keys(src.text).length} text styles → tokens.css, tokens.js`)
