-- =========================================================================
-- Pulse Layer foundation (v5 plan, Phase 1B.1)
-- =========================================================================
-- Foundation schema for the Movement Layer ("Hockia Pulse") — a per-user
-- "what changed in your hockey world since you last visited" feed surface.
-- Cards are generated by event-driven triggers (e.g. profile-viewer events)
-- and by cron-aggregation jobs (e.g. weekly search-appearance summaries).
--
-- This migration ships ONLY the schema:
--   1. user_pulse_items table + RLS + indexes
--   2. Two foundation columns on profiles that downstream Pulse cards will
--      read (availability_confirmed_at, last_meaningful_update_at).
--
-- Helper RPCs (get_my_pulse, mark_pulse_seen/clicked/dismissed) and the
-- frontend feed surface ship in 1B.2. The first card type ships in 1B.3.
-- Cards that don't yet have a generator are silently absent from the feed
-- (the frontend renders "All caught up" when nothing matches).
-- =========================================================================

SET search_path = public;

-- =========================================================================
-- 1. profiles foundation columns
-- =========================================================================
-- Set when user confirms availability via L1 weekly status check-in.
-- NULL = never confirmed (legacy users; the check-in surface treats this
-- as "ask now" rather than "stale").
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS availability_confirmed_at TIMESTAMPTZ;

COMMENT ON COLUMN public.profiles.availability_confirmed_at IS
  'When the user last confirmed availability via the weekly status check-in (L1 loop). NULL = never confirmed. Drives Discovery freshness ranking and reactivation digest copy.';

-- Set by triggers on profile/career/reference/video updates. Drives the
-- P7 Activity Refresh Pulse (>30 days since last meaningful update = nudge).
-- Distinct from updated_at, which moves on any internal trigger touch and
-- isn't a reliable signal of intentional user activity.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_meaningful_update_at TIMESTAMPTZ;

COMMENT ON COLUMN public.profiles.last_meaningful_update_at IS
  'Updated by triggers on user-driven profile + career + reference + video changes. Distinct from updated_at (which moves on any internal touch). Drives P7 Activity Refresh Pulse and Snapshot recency.';

-- =========================================================================
-- 2. user_pulse_items table
-- =========================================================================
-- One row per Pulse card per user. Generated by triggers (event-driven)
-- and cron jobs (cron-driven). Lifecycle timestamps capture funnel state:
--   created_at         → card produced
--   seen_at            → user opened the feed and the card was rendered
--   clicked_at         → user tapped the CTA
--   action_completed_at → the suggested action was actually taken
--   dismissed_at       → user explicitly dismissed
-- Distinct timestamps so analytics can measure each step (e.g. seen→
-- clicked rate, clicked→action_completed rate).
--
-- item_type is TEXT (not an ENUM) for forward-compat: new card types can
-- ship without a schema migration. The frontend's HomeFeedItemCard-style
-- dispatcher renders known types and reports unknown types to Sentry.
CREATE TABLE IF NOT EXISTS public.user_pulse_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,
  -- Drives feed sort tie-break when two cards share a created_at within
  -- the same fetch. 1=highest, 5=lowest. Default 3 = neutral mid-band.
  priority SMALLINT NOT NULL DEFAULT 3 CHECK (priority BETWEEN 1 AND 5),
  -- Card payload (counts, identities, links). Schema is per-card-type and
  -- documented in the matching frontend renderer; not enforced at the DB
  -- level so card types can evolve without migrations.
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  seen_at TIMESTAMPTZ,
  clicked_at TIMESTAMPTZ,
  action_completed_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ
);

COMMENT ON TABLE public.user_pulse_items IS
  'Per-user "what changed since you last visited" Pulse cards (v5 plan Movement Layer). Generated by triggers (event-driven) and cron jobs (cron-driven). Owner-only read via RLS; inserts come from service-role contexts.';

-- =========================================================================
-- 3. Indexes
-- =========================================================================
-- Frontend "Since you last visited" fetch: active (non-dismissed) cards
-- for a user, newest first. Bounded by hard limit in the RPC.
CREATE INDEX IF NOT EXISTS idx_user_pulse_user_active
  ON public.user_pulse_items (user_id, created_at DESC)
  WHERE dismissed_at IS NULL;

-- Analytics: count by item_type within a time window. Cron observability.
CREATE INDEX IF NOT EXISTS idx_user_pulse_type_created
  ON public.user_pulse_items (item_type, created_at DESC);

-- =========================================================================
-- 4. Row-Level Security
-- =========================================================================
ALTER TABLE public.user_pulse_items ENABLE ROW LEVEL SECURITY;

-- Owners read their own pulse items. Nobody else — viewer-identity data
-- inside metadata could leak otherwise.
DROP POLICY IF EXISTS user_pulse_items_select_self ON public.user_pulse_items;
CREATE POLICY user_pulse_items_select_self
  ON public.user_pulse_items
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Owners can update lifecycle timestamps on their own cards (mark seen,
-- mark clicked, dismiss). The helper RPCs in 1B.2 will use SECURITY
-- DEFINER + a strict columns-allowed pattern to prevent owners from
-- editing item_type / metadata / etc.
DROP POLICY IF EXISTS user_pulse_items_update_self ON public.user_pulse_items;
CREATE POLICY user_pulse_items_update_self
  ON public.user_pulse_items
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No INSERT or DELETE policies for authenticated — those operations come
-- from service-role contexts (cron, triggers). Service role bypasses RLS.

GRANT SELECT, UPDATE ON public.user_pulse_items TO authenticated;
