// GENERATED by scripts/build-tokens.mjs from figma-export.json — do not edit by hand.
export const colors = {
  "brand": {
    "primary": "#6c2bd9",
    "primary-hover": "#5b21b6",
    "primary-pressed": "#4c1d95",
    "soft": "#f1eafd",
    "soft-hover": "#e6dafb",
    "soft-pressed": "#e0d3fa"
  },
  "ink": {
    "primary": "#0f0f14",
    "secondary": "#5b5b6b",
    "tertiary": "#6f6f7c",
    "quaternary": "#aeaeb2",
    "inverse": "#ffffff"
  },
  "surface": {
    "base": "#ffffff",
    "subtle": "#f8f8fa",
    "muted": "#f4f4f7",
    "muted-pressed": "#e6e6ec",
    "inverse": "#0f0f14"
  },
  "line": {
    "default": "#e6e6ec"
  },
  "status": {
    "positive": "#15803d",
    "positive-soft": "#e8f7ee",
    "warning": "#b45309",
    "warning-soft": "#fdf1e4",
    "danger": "#dc2626",
    "danger-strong": "#b91c1c",
    "danger-soft": "#fdecec"
  },
  "focus": {
    "ring": "#6c2bd9"
  },
  "overlay": {
    "scrim": "#0f0f1466"
  },
  "media": {
    "placeholder": "#1c1b22"
  },
  "accent": {
    "pink": "#be185d",
    "pink-soft": "#fce7f3",
    "cyan": "#0891b2",
    "cyan-soft": "#e0f4f9",
    "gold": "#c9a227",
    "gold-ink": "#7a5f0b",
    "gold-ink-2": "#9a7a12",
    "gold-soft": "#fff8dc",
    "gold-soft-2": "#fbf4dc",
    "indigo": "#4f46e5",
    "indigo-soft": "#e8e7fd",
    "blue": "#0a7aff",
    "blue-ink": "#1d4ed8",
    "blue-soft": "#e5f1ff",
    "blue-soft-2": "#dbeafe",
    "teal": "#0f766e",
    "teal-soft": "#e0f2f1",
    "orange": "#ea580c",
    "orange-soft": "#fdebdd"
  },
  "social": {
    "instagram": "#e1306c",
    "linkedin": "#0a66c2",
    "facebook": "#1877f2"
  }
}

export const space = {
  "2": 2,
  "4": 4,
  "6": 6,
  "8": 8,
  "12": 12,
  "16": 16,
  "20": 20,
  "24": 24,
  "32": 32,
  "40": 40
}

export const radius = {
  "sm": 8,
  "md": 12,
  "lg": 16,
  "xl": 20,
  "full": 999
}
